spring:
  application:
    name: product-info
 
  sleuth:
    opentracing:
     enabled: true #default : true
    sampler:
      probability: 1.0
      
  zipkin:
    base-url: http://211.253.24.172:10012/
    #private ip
    #base-url: http://172.27.1.7:9411/
    locator:
      discovery:
        enabled: true

  cloud:
    inetutils:
      ignored-interfaces:
      - docker0
      - veth.*
      preferred-networks:
      - 172.27
      use-only-site-local-interfaces: true

            
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://211.253.24.172:8761/eureka/}

server:
  port: ${PORT:8080}


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"