spring:
  application:
    name: product-info
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

server:
  port: ${PORT:8071}


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"