FROM tomcat:jre11-temurin-focal
#FROM tomcat:8.5.71-jre11-temurin

EXPOSE 8080

#RUN rm -rf /usr/local/tomcat/webapps/*
RUN cp -r /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps/
ARG WAR_FILE=target/*.war
COPY ./target/product-view-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/product.war

CMD ["catalina.sh", "run"]
