spring:
  application:
    name: product-inventory

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

server:
  port: ${PORT:8051}


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"