spring:
  application:
    name: product-review
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://211.253.24.172:8761/eureka/}

server:
  port: ${PORT:8080}
